/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.java.mcve;


import org.jooq.mcve.java.mcve.tables.Test;


/**
 * Convenience access to all tables in MCVE.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>MCVE.TEST</code>.
     */
    public static final Test TEST = Test.TEST;
}
