/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.kotlin.domains


import java.time.OffsetDateTime

import org.jooq.Domain
import org.jooq.Schema
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.LazySchema
import org.jooq.impl.LazySupplier
import org.jooq.impl.SQLDataType
import org.jooq.mcve.kotlin.Public



/**
 * The domain <code>PUBLIC.DOMAINTS</code>.
 */
val DOMAINTS: Domain<OffsetDateTime> = Internal.createDomain(
      schema()
    , DSL.name("DOMAINTS")
    , SQLDataType.TIMESTAMPWITHTIMEZONE(32).nullable(false)
)

private fun schema(): Schema = LazySchema(DSL.name("PUBLIC"), DSL.comment(""), LazySupplier { Public.PUBLIC })
