/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.scala


import java.time.OffsetDateTime

import org.jooq.Domain
import org.jooq.Schema
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.LazySchema
import org.jooq.impl.SQLDataType


/**
 * Convenience access to all Domains in PUBLIC.
 */
object Domains {

  /**
   * The domain <code>PUBLIC.DOMAINTS</code>.
   */
  val DOMAINTS: Domain[OffsetDateTime] = Internal.createDomain(
      schema
    , DSL.name("DOMAINTS")
    , SQLDataType.TIMESTAMPWITHTIMEZONE(32).nullable(false)
  )

  private def schema: Schema = new LazySchema(DSL.name("PUBLIC"), DSL.comment(""), () => Public.PUBLIC)
}
