/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.scala


import org.jooq.Index
import org.jooq.OrderField
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.mcve.scala.tables.FlywaySchemaHistory


/**
 * A class modelling indexes of tables in PUBLIC.
 */
object Indexes {

  // -------------------------------------------------------------------------
  // INDEX definitions
  // -------------------------------------------------------------------------

  val FLYWAY_SCHEMA_HISTORY_S_IDX: Index = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, Array[OrderField [_] ](FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS), false)
}
