/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.scala


import java.util.Arrays
import java.util.List

import org.jooq.Catalog
import org.jooq.Domain
import org.jooq.Table
import org.jooq.impl.SchemaImpl
import org.jooq.mcve.scala.tables.FlywaySchemaHistory
import org.jooq.mcve.scala.tables.Test


object Public {

  /**
   * The reference instance of <code>PUBLIC</code>
   */
  val PUBLIC = new Public
}

/**
 * This class is generated by jOOQ.
 */
class Public extends SchemaImpl("PUBLIC", DefaultCatalog.DEFAULT_CATALOG) {

  /**
   * The table <code>PUBLIC.flyway_schema_history</code>.
   */
  def FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY

  /**
   * The table <code>PUBLIC.TEST</code>.
   */
  def TEST = Test.TEST

  override def getCatalog: Catalog = DefaultCatalog.DEFAULT_CATALOG

  override def getDomains: List[Domain[_]] = {
    return Arrays.asList[Domain[_]](
      Domains.DOMAINTS)
  }

  override def getTables: List[Table[_]] = {
    return Arrays.asList[Table[_]](
      FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
      Test.TEST)
  }
}
