/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.scala


import org.jooq.mcve.scala.tables.FlywaySchemaHistory
import org.jooq.mcve.scala.tables.Test


/**
 * Convenience access to all tables in PUBLIC.
 */
object Tables {

  /**
   * The table <code>PUBLIC.flyway_schema_history</code>.
   */
  def FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY

  /**
   * The table <code>PUBLIC.TEST</code>.
   */
  def TEST = Test.TEST
}
