/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.java.public_.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum Enumdomain implements EnumType {

    x("x"),

    y("y");

    private final String literal;

    private Enumdomain(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "ENUMDOMAIN";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
