/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.java;


import java.time.OffsetDateTime;

import org.jooq.Domain;
import org.jooq.Schema;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.LazySchema;
import org.jooq.impl.LazySupplier;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all Domains in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Domains {

    /**
     * The domain <code>PUBLIC.DOMAINTS</code>.
     */
    public static final Domain<OffsetDateTime> DOMAINTS = Internal.createDomain(
          schema()
        , DSL.name("DOMAINTS")
        , SQLDataType.TIMESTAMPWITHTIMEZONE(32).nullable(false)
    );

    private static final Schema schema() {
        return new LazySchema(DSL.name("PUBLIC"), DSL.comment(""), new LazySupplier<Schema>() {
            @Override
            public Schema get() {
                return Public.PUBLIC;
            }
        });
    }
}
