/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.java;


import org.jooq.mcve.java.tables.FlywaySchemaHistory;
import org.jooq.mcve.java.tables.Test;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>PUBLIC.TEST</code>.
     */
    public static final Test TEST = Test.TEST;
}
