/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.kotlin.tables


import java.time.OffsetDateTime

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row2
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.jooq.mcve.kotlin.Public
import org.jooq.mcve.kotlin.tables.records.TestRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Test(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, TestRecord>?,
    aliased: Table<TestRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<TestRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>PUBLIC.TEST</code>
         */
        val TEST = Test()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TestRecord> = TestRecord::class.java

    /**
     * The column <code>PUBLIC.TEST.DOMAINTSVALUE</code>.
     */
    val DOMAINTSVALUE: TableField<TestRecord, OffsetDateTime?> = createField(DSL.name("DOMAINTSVALUE"), org.jooq.mcve.kotlin.domains.DOMAINTS.getDataType(), this, "")

    /**
     * The column <code>PUBLIC.TEST.LOCALTSVALUE</code>.
     */
    val LOCALTSVALUE: TableField<TestRecord, OffsetDateTime?> = createField(DSL.name("LOCALTSVALUE"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    private constructor(alias: Name, aliased: Table<TestRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<TestRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>PUBLIC.TEST</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>PUBLIC.TEST</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>PUBLIC.TEST</code> table reference
     */
    constructor(): this(DSL.name("TEST"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, TestRecord>): this(Internal.createPathAlias(child, key), child, key, TEST, null)
    override fun getSchema(): Schema = Public.PUBLIC
    override fun `as`(alias: String): Test = Test(DSL.name(alias), this)
    override fun `as`(alias: Name): Test = Test(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Test = Test(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Test = Test(name, null)

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row2<OffsetDateTime?, OffsetDateTime?> = super.fieldsRow() as Row2<OffsetDateTime?, OffsetDateTime?>
}
